### PR TITLE
compatiable with xformers

### PR DESCRIPTION
**Pull request by fsx950223**
Add ```__version__``` api

### CODE REVIEW

**Comment by sabreshao** [comment]
@regnnighe is this PR compatible with upstream?

**Comment by regnnighe** [comment]
> @regnnighe is this PR compatible with upstream?

No. Upstream uses a get_version function to get the version info in the __init__.py

**Comment by fsx950223** [comment]
I port get_package_version to setup.py

**Comment by sabreshao** [comment]
LGTM

**Pull request merged**
